# Default values for foobar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tor:
  image:
    repository: "dennajort/tor-client"
    pullPolicy: IfNotPresent
    tag: "0.4.7.8"

image:
  repository: "ruimarinho/bitcoin-core"
  pullPolicy: IfNotPresent
  tag: "23.0"

updateStrategy: Recreate
